{
    'name': 'CMH Equipment',
    'version': '0.1',
    'summary': 'Module to manage CMH activities',
    'description': 'Module to manage cash engine',
    'category': 'CMH',
    'author': 'David Saint-Aignan',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['stock', 'cmh_project', 'product'],
    'data': [
        # 'data/brand.xml',
        # 'data/brand_model.xml',
        # 'data/version.xml',
        # 'data/equipment.xml',
        # 'data/settings.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/menus.xml',
        # 'views/settings.xml',
        'views/equipment_views.xml',
        'views/brand_views.xml',
        'views/brand_model_views.xml',
        'views/version_views.xml',
        'views/equipment_template_views.xml',
        'views/product_views.xml',
    ],
    'demo': [],
    'sequence': 1,
    'application': False,
    'installable': True,
    'auto_install': False,
    # 'post_init_hook': 'set_stock_module_requirements',
}
